version: '{build}'
skip_tags: true
image: Visual Studio 2017
configuration: Release
test_script:
- cmd: dotnet test src/Serilog.Sinks.ApplicationInsights.Tests/Serilog.Sinks.ApplicationInsights.Tests.csproj
build_script:
- ps: ./Build.ps1
artifacts:
- path: artifacts/Serilog.*.nupkg
only_commits:
  files:
    - serilog-sinks-applicationinsights.sln
    - src/Serilog.Sinks.ApplicationInsights/
    - Build.ps1
    - assets/
deploy:
- provider: NuGet
  api_key:
    secure: N59tiJECUYpip6tEn0xvdmDAEiP9SIzyLEFLpwiigm/8WhJvBNs13QxzT1/3/JW/
  skip_symbols: true
  on:
    branch: /^(master|dev)$/
- provider: GitHub
  auth_token:
    secure: p4LpVhBKxGS5WqucHxFQ5c7C8cP74kbNB0Z8k9Oxx/PMaDQ1+ibmoexNqVU5ZlmX
  artifact: /Serilog.*\.nupkg/
  tag: v$(appveyor_build_version)
  on:
    branch: master